Add and remove devices to routine
pedrohlucena/challenge-brq pull request #3
Opened 2022-10-02 02:42 UTC by cgodevs

JS script and HTML page were implemented and seem to be fully functional! :D

2022-10-02 14:42 UTC, pedrohlucena requested changes

2022-10-02 14:42 UTC, pedrohlucena commented on screens/list-of-rotines/index.html
> +<!DOCTYPE html>
Esse arquivo é meu, não é pra ter ele na sua PR

2022-10-02 14:42 UTC, pedrohlucena commented on screens/create-routine/index.html
> +<html lang="en">
Aqui coloca `<html lang="pt-BR">`

2022-10-02 14:42 UTC, pedrohlucena commented on screens/create-routine/index.html
> +    <title>Listagem de rotinas</title>
Aqui deve ser "Criar nova rotina"

2022-10-02 14:42 UTC, pedrohlucena commented on screens/create-routine/index.html
> +    <link rel="stylesheet" href="../../assets/css/index.css">
Tira esse `rel="stylesheet"` quando vocẽ coloca isso você está dizendo que o arquivo que você está importando é um arquivo de estilo e aqui esse não é o caso

2022-10-02 14:42 UTC, pedrohlucena commented on screens/create-routine/index.html
> +                <option value="horario">Em horário específico</option>
Quando essa opção abre o usuário deve poder escolher se ele quer em um horário específico, porém também pode escolher se ele quer em um horário específico em certos dias da semana

Exemplo: De segunda a sexta-feira, às 17:45h

To falando isso principalmente por esse insight que nós temos:

![image](https://user-images.githubusercontent.com/85816124/193457017-da136c8b-0825-4251-a168-f565c07b5e31.png)

E apenas com esse campo que você colocou o usuário nem conseguiria criar esse rotina que nós pré definimos

2022-10-02 14:42 UTC, pedrohlucena commented on screens/create-routine/index.html
> +                <option value="horario">Em horário específico</option>
Caso não tenha entendido só falar que vamos canal

2022-10-02 14:42 UTC, pedrohlucena commented on screens/create-routine/index.html
> +              <input type="email" class="form-control" id="nome-rotina" placeholder="">
Aqui você deixou que o tipo do input é email, tem que tirar isso.

Se você deixar o usuário vai ter que criar rotinas com @ no nome eisso é nada a ver

Peguei esse bug testando sua tela
![image](https://user-images.githubusercontent.com/85816124/193457206-3c95f7de-ed3f-4d14-be50-3bcdb594fc21.png)

2022-10-02 14:42 UTC, pedrohlucena commented on js/create-routine.js
> +var todosDispositivos = ["Ar Condicionado", "Câmera", "Lâmpada",  "Rádio", "TV"];
Eu separaria esse código mais, separaria em funções, ele ta muito grudado, todas as funções em um arquivo só fica ruim

2022-10-02 14:42 UTC, pedrohlucena commented on screens/create-routine/create-routine.html
> +<!DOCTYPE html>
O nome do arquivo da sua tela deve ser "index.html", você poderia trocar pf?

Aí a sua pasta create-routine só teria um único arquivo, o index.html , com o código da sua tela

2022-10-02 14:42 UTC, pedrohlucena commented on js/create-routine.js
> +var todosDispositivos = ["Ar Condicionado", "Câmera", "Lâmpada",  "Rádio", "TV"];
Adiciona a opção "caixinha de som" como um dispositivo, para que a gente consiga criar esse rotina que foi pré definida por nós

![image](https://user-images.githubusercontent.com/85816124/193457752-9b332253-8242-4af3-87b9-a576c764d22f.png)

2022-10-02 14:42 UTC, pedrohlucena commented on screens/create-routine/index.html
> +              <select class="form-control" id="tipo-acionamento" onchange="abreNovoCampoAcao()">
Aqui teríamos que ter uma opção "Próximos X dias" ou algo do tipo, isso para que a gente consiga criar esse rotina que foi pré estabelecida por nós.

![image](https://user-images.githubusercontent.com/85816124/193457803-f30a6d62-f6d3-4ba4-b9c9-c8ac1c78680b.png)

2022-10-02 14:42 UTC, pedrohlucena commented on screens/create-routine/index.html
> +              <select class="form-control" id="tipo-acionamento" onchange="abreNovoCampoAcao()">
Quando você for criar essa opção, coloca uma opção de "Dias úteis", para que o usuário não precisa ficar selencionando: Segunda, terça, quarta ... aí o dias úteis já resolve

2022-10-02 14:42 UTC, pedrohlucena commented on js/create-routine.js
> +var todosDispositivos = ["Ar Condicionado", "Câmera", "Lâmpada",  "Rádio", "TV"];
Troca "Ar condicionado" por "Ar-condicionado", acho que fica melhor.

E CASO DE TEMPO, tenta corrigir o porquê dele não estar exibindo caracteres acentuados no front
![image](https://user-images.githubusercontent.com/85816124/193458216-1baa95b4-e880-4ad4-a1fc-d2923348f6ed.png)

2022-10-02 14:42 UTC, pedrohlucena commented on screens/create-routine/create-routine.html
> +            <label for="botao_seleciona_dispositivo">Adicionar Dispositivo</label>
Seria interessante se tivéssemos uma opção mais fácil pro usuários caso ele queira ligar/desligar todos os dispositivos da casa. Isso ao invés dele fazer isso manualmente adicionando os dispositivos com o "ligar/desligar" de forma manual, entende?

Se não entender vamo canal

2022-10-02 14:42 UTC, pedrohlucena commented on screens/create-routine/index.html
> +                <option value="distancia">Conforme distância da residência</option>
Eu trocaria isso por "À determinada distância da casa", fica mais intuitivo

2022-10-02 14:42 UTC, pedrohlucena commented on js/create-routine.js
> +                        <option value="">Próximos 3 dias</option>
Eu não to conseguindo abrir essas opções no frontend, elas não aparecem pra mim ;-;

2022-10-02 14:42 UTC, pedrohlucena commented on screens/create-routine/create-routine.html
> +                <option value="horario">Em horário específico</option>
Deixa aqui como "Informe o horário de disparo da rotina" pra ficar mais claro

![image](https://user-images.githubusercontent.com/85816124/193458700-90176e79-d204-4337-a15b-84c6ff36dbfb.png)

2022-10-02 14:42 UTC, pedrohlucena commented on js/create-routine.js
> +            <label for="certa_distancia">🛣️ Defina a distância (em metros) desejada de sua casa:</label>
Troca aqui por "Defina a que distância de sua casa a rotina deve ser acionada (em metros): "

2022-10-02 14:42 UTC, pedrohlucena commented on js/create-routine.js
> +            <label for="certa_distancia">⏱️ Defina a quantos minutos de sua casa:</label>
Defina a quanto tempo de sua casa a rotina deve ser acionada (em minutos):

2022-10-02 14:42 UTC, pedrohlucena commented on js/create-routine.js
> +            <label for="certa_distancia">⏱️ Defina a quantos minutos de sua casa:</label>
O emoji não está sendo passado para o front

2022-10-02 14:42 UTC, pedrohlucena commented on js/create-routine.js
> +                                            ${dispositivosAindaDisponiveis.length} Dispositivos Disponíveis:
Troca aqui por "Dispositivos ainda disponíveis"

2022-10-02 14:42 UTC, pedrohlucena commented on js/create-routine.js
> +                                        <select class="form-control" >
Caso o usuário selecione "Ar-condicionado" para dispositivo, seria interessante que a gente adicionasse outro input em baixo com "Você deseja ligar o ar-condicionado em que temperatura?" e uma input pra ele digitar a que temperatura ele deseja ligar o ar-condicionado

2022-10-02 14:42 UTC, pedrohlucena commented on js/create-routine.js
> +                                            ${dispositivosAindaDisponiveis.length} Dispositivos Disponíveis:
Considera exibir os dispositivos ainda disponíveis assim:

Ar-condicionado
Lâmpada
Câmera
Rádio
TV

Que aí fica ordenado do mais longo em questão de caracteres pro menos longo

2022-10-02 14:42 UTC, pedrohlucena commented on js/create-routine.js
> +                                            ${dispositivosAindaDisponiveis.length} Dispositivos Disponíveis:
Eu não sei se esse era o comportamento que você esperava, mas se eu seleciono ele continua podendo ser selecionado, não sei se é isso mesmo ou se ele deveria não poder ser mais selecionado

Se não entender vamo canal

![image](https://user-images.githubusercontent.com/85816124/193459481-ae0aae96-f757-4378-a4eb-290a3492514e.png)

2022-10-02 14:42 UTC, pedrohlucena commented on js/create-routine.js
> +var dispositivosSelecionados = [];
VOCÊ NÃO PRECISA TROCAR, porém fica como alerta que o var" quase não é mais utilizado para definição de variáveis

Para variáveis prefira usar "let" e "const", vídeo caso você queira aprender mais sobre isso:
https://www.youtube.com/watch?v=ZOx7iTnBqFQ

2022-10-02 14:42 UTC, pedrohlucena commented on assets/css/index.css
> +@import url('./fonts.css');
Esse aqui era eu que tinha criado, você deve excluí-lo, a menos que você tenha algo que é do seu código no index.css

2022-10-02 14:42 UTC, pedrohlucena commented on assets/css/fonts.css
> +body {
Esse aqui era eu que tinha criado, você deve excluí-lo

2022-10-02 14:42 UTC, pedrohlucena commented on assets/css/colors.css
> +}
Esse aqui era eu que tinha criado, você deve excluí-lo

2022-10-02 14:42 UTC, pedrohlucena commented on assets/css/buttons.css
> +.btn-primary, .btn-primary:hover, .btn-primary:active, .btn-primary:visited, .btn-primary:focus, .btn-primary:active {
Esse aqui era eu que tinha criado, você deve excluí-lo

2022-10-02 21:23 UTC, pedrohlucena approved these changes

2022-10-04 23:23 UTC, mateusfv requested changes

2022-10-04 23:23 UTC, mateusfv commented on screens/create-routine/index.html
> +              <label for="tipo-acionamento">Tipo de Acionamento</label>
Isto está certo, o acionamento da Rotina (Journey) pode ser Manual ou Automático, mas esse último faz referência somente a uma hora especificada pelo usuário. 
O que é "acionado" por, e somente por, "minutos de distância" da casa são os dispositivos inclusos na Rotina, cada um com sua quantidade de minutos escolhida pelo usuário.
O "A determinada distância da casa" pode ser apagado.

2022-10-05 01:05 UTC, mateusfv approved these changes

2022-10-05 11:11 UTC, closed without merging