Entrega da tela "Configurações".
pedrohlucena/challenge-brq pull request #4
Opened 2022-10-02 19:16 UTC by eduardadev

2022-10-02 19:46 UTC, pedrohlucena requested changes

2022-10-02 19:46 UTC, pedrohlucena commented on screens/app_configuration/index.html
> +  <div class="p-2"><a href="./home.html"><img src="../../assets/images/botaoretornar.svg" id="botaoretorno"></a></div>
Aqui o href deve ser `href="../home/index.html"`

2022-10-02 19:46 UTC, pedrohlucena commented on screens/app_configuration/index.html
> +  <div class="p-2"><a href="./home.html"><img src="../../assets/images/botaoretornar.svg" id="botaoretorno"></a></div>
Para que ele de fato leve pra tela home do Mateus

2022-10-02 19:46 UTC, pedrohlucena commented on assets/css/eduarda.css
> +    background-color: black;
Aqui a cor não é preto, é a cor #15161a

2022-10-02 19:46 UTC, pedrohlucena commented on assets/css/eduarda.css
> +h1{
Você pode criar um arquivo text.css na pasta css com as os estilos relacionados a texto, aí você coloca os estilos do:
- h1
- h5

2022-10-02 19:46 UTC, pedrohlucena commented on assets/css/eduarda.css
> +.btn-outline-primary{
Você pode criar o buttons.css e jogar os estilo do botaoretorno , do btn-outline-primary e do btn-outline-primary:hover

2022-10-02 19:46 UTC, pedrohlucena commented on assets/css/eduarda.css
> +
Depois que você fizer tudo que eu listei acima, você vai criar o index.css e importar todos os estilos que estão na sua pasta .css , ele meio que vai centralizar todos os estilos que você criou em um único arquivo, beleza?

Ok, você te um index.css com todos os seus estilos, é esse arquivo que você deve importar no index.html , com isso a importação de arquivo de estilo fica mais limpa, ao invés de importar 30 arquivos, você importa um apenas, que nesse arquivo importa todos os seus arquivos de estilo, beleza?

A sintaxe de importação que você deve usar no index.css é assim:

@import url('./fonts.css');
@import url('./buttons.css');
@import url('./colors.css');

Onde o './colors.css' vai ser o path para os arquivos da sua pasta .css

2022-10-02 19:46 UTC, pedrohlucena commented on assets/css/eduarda.css
> +body{
Você pode jogar essa estilização do body em um arquivo general.css , onde terão configurações gerais que vão valer para todas as telas, aí depois você importa esse arquivo general.css no index.css também
(Se você não entender o que eu falei continua lendo isso aqui que eu você vai entender)

2022-10-02 19:46 UTC, pedrohlucena commented on screens/app_configuration/index.html
> +<html lang="en">
Aqui deve ser `<html lang="pt-BR">`

2022-10-02 19:46 UTC, pedrohlucena commented on screens/app_configuration/index.html
> +    <title>Home</title>
Aqui o texto deve mudar para "Configurações" ao invés de "Home"

2022-10-02 19:46 UTC, pedrohlucena commented on screens/app_configuration/index.html
> +    <link rel="stylesheet" href="../../assets/css/eduarda.css">
Aqui que ficará a importação do index.css que eu mencionei na revisão do arquivo "eduarda.css"

2022-10-02 19:46 UTC, pedrohlucena commented on screens/app_configuration/index.html
> +      <div class="p-2"><button type="button" class="btn btn-outline-primary">Enviar</button></div>
Ao invés de 3 botões enviar você pode criar um único nessa posição aqui. Nisso, quando você clicar, o botão deve limpar todos os valores que estão nos inputs, isto é, se os inputs estavam com algum texto, eles devem ficar vazios após o botão ser clicado

![image](https://user-images.githubusercontent.com/85816124/193473154-a5fa60b0-62bf-4579-b9d7-b82c3e4d2afe.png)

2022-10-02 19:46 UTC, pedrohlucena commented on screens/app_configuration/index.html
> +      <div class="p-2"><input type="text" class="form-control"></div>
Aqui seria interessante que os inputs tivessem o mesmo tamanho

![image](https://user-images.githubusercontent.com/85816124/193473238-21183687-611b-4216-afdc-5ba70968284e.png)

2022-10-02 19:46 UTC, pedrohlucena commented on screens/app_configuration/index.html
> +</html>
Seu código ficou limpin, parabéns!

2022-10-02 20:18 UTC, eduardadev commented on screens/app_configuration/index.html
> +      <div class="p-2"><input type="text" class="form-control"></div>
esse no meu n ta assim

2022-10-02 20:34 UTC, eduardadev commented on assets/css/eduarda.css
> +    background-color: black;
ok

2022-10-02 22:09 UTC, cgodevs commented on screens/app_configuration/index.html
> +  <div class="p-2"><a href="./home.html"><img src="../../assets/images/botaoretornar.svg" id="botaoretorno"></a></div>
como o nome do arquivo de imagem mudou, aqui está apontando para outro caminho, não aparece a img
![image](https://user-images.githubusercontent.com/69640514/193478454-81a29e1b-c44f-421b-9dfb-6c8a776fbcfe.png)

Por isso deve ser **<img src="../../assets/images/return-button.svg" id="botaoretorno">**

2022-10-03 22:56 UTC, pedrohlucena approved these changes

2022-10-03 22:59 UTC, cgodevs approved these changes
Boa!

2022-10-03 22:59 UTC, cgodevs commented on screens/app_configuration/index.html
> +  <div class="p-2"><a href="./home.html"><img src="../../assets/images/botaoretornar.svg" id="botaoretorno"></a></div>
como o nome do arquivo de imagem mudou, aqui está apontando para outro caminho e não aparece a img, ficou assim: 
![image](https://user-images.githubusercontent.com/69640514/193478500-20bc2a4e-c798-4a92-9415-aa0998e12cc4.png)

trocar para 
**src="../../assets/images/return-button.svg"**

2022-10-03 22:59 UTC, cgodevs commented on screens/app_configuration/index.html
> +      <div class="p-2"><button type="button" class="btn btn-outline-primary">Enviar</button></div>
O que acha de trocar "Enviar" por "Definir"?

2022-10-03 23:08 UTC, merged